---
title: "Certification: Caseflow Use After CSS Transition"
output: 
  html_notebook: 
    code_folding: hide
---

```{r include = FALSE}
source("../R/vacolsConnect.R")
library("dplyr")
library("tidyr")
library("knitr")
library("scales")

con <- vacolsConnect()
```

## Objective

Compare RO use of Caseflow before and after the CSS transition.

Only includes paperless (VBMS) cases. Pre-CSS group includes certifications since July 1, 2016.

```{r}
ro <- read.csv("../data/ro.csv", stringsAsFactors = FALSE)

uptake <- dbGetQuery(con, "
  select
    BF41STAT,
    BFDCERTOOL,
    BFREGOFF
  
  from BRIEFF
  
  join FOLDER
    on BFKEY = TICKNUM
  
  where TIVBMS in ('Y', '1', '0')
    and BF41STAT >= date '2016-07-01'
") %>%
  mutate(
    caseflow = ifelse(is.na(BFDCERTOOL), "Not_Caseflow", "Caseflow"),
    group = ifelse(BF41STAT < as.POSIXct("2016-10-17"), "pre", paste0("week", floor((as.Date(BF41STAT) - as.Date("2016-10-17")) / 7) + 1))
  ) %>%
  count(BFREGOFF, caseflow, group) %>%
  spread(caseflow, n, fill = 0) %>%
  ungroup() %>%
  transmute(
    BFREGOFF,
    group,
    Percent_Caseflow = Caseflow / (Caseflow + Not_Caseflow)
  ) %>%
  spread(group, Percent_Caseflow) %>%
  mutate(max_post = pmax(week1, week2, week3, week4, na.rm = TRUE)) %>%
  arrange(-max_post) %>%
  mutate_each(funs(percent), pre, starts_with("week"), max_post) %>%
  left_join(ro, by = c("BFREGOFF")) %>%
  select(-week5, -Station)

kable(uptake)
```
