---
title: "Certification: Caseflow Use by RO"
output: 
  html_notebook: 
    code_folding: hide
---

```{r include = FALSE}
source("../R/vacolsConnect.R")
library("dplyr")
library("tidyr")
library("knitr")
library("scales")

con <- vacolsConnect()
```

## Objective

Identify ROs that have lower uptake of Caseflow Certification, or are frequently overriding it.

Only includes paperless (VBMS) cases from Q4 FY16.

```{r}
ro <- read.csv("../data/ro.csv", stringsAsFactors = FALSE)

uptake <- dbGetQuery(con, "
  select
    BF41STAT,
    BFDCERTOOL,
    BFREGOFF
  
  from BRIEFF
  
  join FOLDER
    on BFKEY = TICKNUM
  
  where TIVBMS in ('Y', '1', '0')
    and BF41STAT > date '2016-07-01' and BF41STAT < date '2016-10-01'
") %>%
  mutate(caseflow = ifelse(is.na(BFDCERTOOL), "Not_Caseflow", "Caseflow")) %>%
  count(BFREGOFF, caseflow) %>%
  spread(caseflow, n, fill = 0) %>%
  mutate(
    Total = Caseflow + Not_Caseflow,
    Percent_Caseflow = percent(Caseflow / Total)
  ) %>%
  left_join(ro, by = c("BFREGOFF")) %>%
  select(-Station) %>%
  arrange(desc(Total))

kable(uptake)
```
