---
title: "Dispatch: Time to Claim Establishment (Creation of End Product in VBMS)"
output: 
  html_notebook: 
    code_folding: hide
---

```{r include = FALSE}
source("../R/vacolsConnect.R")
library("dplyr")

con <- vacolsConnect()
```

## Objective

## Status

**In Progress**

## Results

```{r}
vacols_decisions <- dbGetQuery(con, "
  select
    BFKEY,
    BFDNOD,
    BFDDEC,
    BFCORLID,
    BFMPRO,
    BFREGOFF,
    BFAC,
    BFDC,
    LOCSTTO as EPLOC,
    VACOLS.ISSUE_CNT_ALLOWED(bfkey) as ALLOWED,
    VACOLS.ISSUE_CNT_REMAND(bfkey) as REMANDED

  from BRIEFF

  left join
  (
    select
      LOCKEY as MLOCKEY,
      max(LOCDOUT) MLOCDOUT

    from PRIORLOC
    where LOCSTTO in ('50', '51', '54', '70', '97', '98')
    group by LOCKEY
  ) on MLOCKEY = BFKEY

  left join PRIORLOC
    on LOCKEY = BFKEY and LOCDOUT = MLOCDOUT

  where (BFDC = '1' or BFDC = '3')
    and BFAC <> '7'
    and BFDDEC >= date '2015-10-01' and BFDDEC < date '2016-10-01'
") %>%
  mutate(
    case_decision_date = as.Date(BFDDEC),
    disposition = ifelse(REMANDED > 0 & ALLOWED > 0, "Partial Grant", ifelse(REMANDED == 0, "Full Grant", "Remand"))
  )

# Doesn't work because bundler, gemfile contents not installed
# claims <- system("ruby ./ruby/claims_for_bfcorlid.rb", intern = TRUE, input = unique(decisions$BFCORLID))

write.table(unique(decisions$BFCORLID), "../tmp/cases.txt", quote = FALSE, row.names = FALSE, col.names = FALSE)

# Run the ruby script manually

claims <- read.csv("../tmp/claims.csv", stringsAsFactors = FALSE)

merged_decisions_claims <- vacols_decisions %>%
  inner_join(claims, by = c("BFCORLID")) %>%
  mutate(
    claim_decision_date = as.Date(claim_receive_date, "%m/%d/%Y"),
    journal_date = as.Date(journal_date, "%m/%d/%Y"),
    precise_match = case_decision_date == claim_decision_date,
    fuzzy_match = !precise_match & abs(case_decision_date - claim_decision_date) <= 31
  ) %>%
  filter(precise_match | fuzzy_match)

decision_claim_matches <- merged_decisions_claims %>%
  select(BFCORLID, BFDDEC, precise_match, fuzzy_match) %>%
  group_by(BFCORLID, BFDDEC) %>%
  summarise(has_match = TRUE, has_precise_match = sum(precise_match) > 0)

merged_decisions_claims %<>%
  left_join(decision_claim_matches, by = c("BFCORLID", "BFDDEC")) %>%
  filter(precise_match | (fuzzy_match & !has_precise_match))

merged_decisions_claims$journal_date[merged_decisions_claims$journal_date < merged_decisions_claims$case_decision_date] <- NA

merged_decisions_claims %<>%
  group_by(BFCORLID, BFDDEC) %>%
  slice(which.min(ifelse(is.na(journal_date), 0, journal_date))) %>%
  select(BFCORLID, BFDDEC, has_match, has_precise_match, benefit_claim_id, claim_decision_date, journal_date, journal_object_id, journal_station, journal_user_id, claim_type_code, claim_type_name, end_product_type_code, status_type_code)

decisions <- vacols_decisions %>%
  group_by(BFCORLID, BFDDEC) %>%
  mutate(multi_decision = n() > 1) %>%
  ungroup() %>%
  left_join(merged_decisions_claims, by = c("BFCORLID", "BFDDEC")) %>%
  mutate(
    time_to_ep = journal_date - case_decision_date,
    amc_ep = journal_station == 397
  )

clean_decisions <- filter(decisions, !multi_decision, !is.na(time_to_ep))

tapply(clean_decisions$time_to_ep, list(clean_decisions$disposition, clean_decisions$amc_ep), median)
tapply(clean_decisions$time_to_ep, list(clean_decisions$disposition, clean_decisions$amc_ep), mean)
```
